### ISSUE TITLE
freegeoip.net offline

### ISSUE THREAD

**Issue by ryanohoro** [HurricaneLabs/machinae#20]
It appears the resource at freegeoip.net has been taken down by the author. It may be time to add a more reliable geolocation option, perhaps one with an API you can subscribe to for volume-heavy work.

An alternative to freegeoip.net was spun up in its place at freegeoip.io, but it's not certain how long that will stay available. 

Reference: https://github.com/fiorix/freegeoip/issues/165

**Comment by mcm** [comment]
Thanks for letting us know. There is an alternative that can be subscribed
to, telize, and I plan to add support for Maxminds API. I'll look into
freegeoip.io.

-- 
Steve McMaster
Security Operations Lead
mcmaster@hurricanelabs.com
Direct: 216.923.1330 x108 <216.923.1330;108>
SOC: 216.923.1330 x4
