### ISSUE TITLE
ThreatExpert output

### ISSUE THREAD

**Issue by Den1al** [HurricaneLabs/machinae#26]
I've scanned for the hash "9749d38ae9b9ddd81b50aad679ee87ec" and ThreatExpert did had output but was not parsed into the output.

the url: http://www.threatexpert.com/report.aspx?md5=9749d38ae9b9ddd81b50aad679ee87ec

**Comment by hurricane-labs-deployment** [comment]
That link takes me to the main search page, and then a search for that hash
returns no results. Am I misunderstanding?

-- 
Steve McMaster
Security Operations Lead
mcmaster@hurricanelabs.com
Direct: 216.923.1330 x108 <216.923.1330;108>
SOC: 216.923.1330 x4

**Comment by Den1al** [comment]
Your right. My mistake.
