### ISSUE TITLE
IPVoid missing output

### ISSUE THREAD

**Issue by Den1al** [HurricaneLabs/machinae#28]
According to the .yaml file, the IPVoid should return the Blacklist status, but it doesn't.
i.e the ip http://www.ipvoid.com/scan/8.8.8.8/ did not return the black list status.

**Comment by mcm** [comment]
@Den1al it only pulls the black list info if the IP is actually listed.

**Comment by Den1al** [comment]
Regardless of the blacklisting status, even knowing that it is safe is good practice.

**Comment by mcm** [comment]
Hmm. Lemme think on that. I agree but I'm not sure how best to visualize that without spitting out a ton of lines for each of their blacklists

**Comment by Den1al** [comment]
What do you mean by tons of lines? There is just one line to add.

**Comment by mcm** [comment]
So currently, if you checked an IP that was listed on any of the lists IPVoid checks, you'd get one line of output for each blacklist they're listed on. The config logic doesn't currently (although maybe this is a feature we'd need for this case) support the "lack" of results - that is, there's no way in a site's configuration to say "If none of these match, say 'Not listed'". Instead, you'd have to list EVERY blacklist, and a status of whether its listed. That list is pretty long.
