### ISSUE TITLE
malc0de domain

### ISSUE THREAD

**Issue by edoz90** [HurricaneLabs/machinae#35]
- regex: '<tr class=\"class1\">\n*\s*<td>\d{4}-\d{2}-\d{2}<\/td>\n*\s*<td>(.+)<\/td>'
      values:
          - malc0de_domain
      pretty_name: "MC Domain"

**Comment by billford** [comment]
Already added it seems.

**Comment by edoz90** [comment]
I don't see any `malc0de_domain` in the source code...

Anyway that regex is so old that I don't know if it's still valid and I don't use anymore machinae
