### ISSUE TITLE
Provide indication of invalid site

### ISSUE THREAD

**Issue by tcwaddell** [HurricaneLabs/machinae#44]
When an invalid site is specified with the '-s' argument, machinae does not give obvious feedback indicating that the site is invalid.

```
user@ubuntu:~$ machinae -s not_a_real_source A8EDE5B4E9AD5F52A3C28142FA26A4C2CAA2D9BD9E73AEAD41942D31986E4ABE
********************************************************************************
* Information for A8EDE5B4E9AD5F52A3C28142FA26A4C2CAA2D9BD9E73AEAD41942D31986E4ABE
* Observable type: hash.sha256 (Auto-detected: True)
********************************************************************************

user@ubuntu:~$
```

**Comment by billford** [comment]
Any preference for message that’s returned?

**Comment by tcwaddell** [comment]
I did not have anything specific in mind.

**Comment by amg4110** [comment]
I think it should say something like:

Error: Invalid source! Please run "machinae --list-sites", pick your poison, and try again.

Or something along those lines. :D

**Comment by billford** [comment]
This entire thing made my eyes bleed. I will need to really really really dig in to make that work correctly and I have it somewhat worked out in a local branch. I added a message for now to check --list-sites if the results aren't what you expect.
